language: node_js
node_js:
- '4'
- '6'
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  # When all dependencies declare bitcore-lib as a peerDependency this can be bumped up, but this matches the current ecosystem version expected by dependencies
  - npm install bitcore-lib@0.13.7
  - npm install
after_script:
  - gulp coveralls
